tools:
  -
    class_name: spectune.tools.verl.SpectuneTool
    config:
      type: native
      tool_name: nmr_generate
  -
    class_name: spectune.tools.verl.SpectuneTool
    config:
      type: native
      tool_name: nmr_repair
  -
    class_name: spectune.tools.verl.SpectuneTool
    config:
      type: native
      tool_name: nmr_rerank
  -
    class_name: spectune.tools.verl.SpectuneTool
    config:
      type: native
      tool_name: nmr_forward_predict
  -
    class_name: spectune.tools.verl.SpectuneTool
    config:
      type: native
      tool_name: reaction_local_index_search
  -
    class_name: spectune.tools.verl.SpectuneTool
    config:
      type: native
      tool_name: askcos_reaction_forward_predict
  -
    class_name: spectune.tools.verl.SpectuneTool
    config:
      type: native
      tool_name: code_interpreter
  -
    class_name: spectune.tools.verl.SpectuneTool
    config:
      type: native
      tool_name: web_search
