"""Refine rollout trajectories into higher-quality multiturn SFT messages.

This module runs after :mod:`spectune.rollout.postprocess` and before SFT.  It
asks a teacher model to rewrite only the reasoning for each assistant turn,
then deterministically combines those rewrites with the original system, user,
tool-call, tool-response, and final-answer data.  The refiner never executes
tools, so existing evidence is never regenerated by the model.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from spectune.format.v1 import (
    SYSTEM_PROMPT_THINK_RDKIT,
    extract_smiles_candidates,
    extract_tool_calls,
    format_final_answer,
)
from spectune.llm import LlmClientProtocol, create_llm_client

from .io import to_python

JsonDict = dict[str, Any]

DEFAULT_MAX_TOKENS = 32768
DEFAULT_BATCH_SIZE = 16

REFINER_PROMPT = """\
你是一名核磁解谱轨迹的推理编辑器。输入 messages 已由程序规范化，其中 system、普通 user、
tool_response、tool_call 和最终 smiles 答案都属于不可修改的证据。你只负责为每条 assistant 消息
重写更长、更完整、更易懂、更详细的中文 reasoning，程序会把 reasoning 与原始工具调用/答案重新拼接。

必须遵守：
1. 只输出合法 JSON，固定形状：
   {"assistant_rewrites": [{"message_index": 2, "reasoning": "..."}, ...]}
   不要输出 Markdown 代码块或额外说明。
2. 必须为输入中每一个 role=assistant 的 message_index 输出且只输出一条 rewrite，顺序与输入一致。
3. reasoning 只写 <think> 内应出现的中文推理正文，不要包含 <think>、<tool_call>、
   <tool_response>、最终答案 JSON 或 messages。
4. 调用工具前应说明已有约束、候选假设、为什么需要该工具以及预期区分什么。
   工具响应后的 reasoning 应解释结果、矛盾、候选排除、错误修正和下一步依据。
5. 最后一条 assistant 的 reasoning 应总结完整证据链、不确定性和候选排序依据。
6. 推理应尽可能充分但不能堆砌空话。优先补全：分子式/DBE、积分与信号计数、官能团和片段约束、
   候选间逐项比较、工具结果的正确解读、失败调用后的修正、仍无法由现有谱图确定的事项，等等。
7. 主动纠正原轨迹中的化学错误，不要因为最终答案碰巧正确就保留错误解释。不得读取或猜测 messages 之外的 ground truth。
8. 不得声称执行输入中不存在的工具，不得改写或重新输出工具证据。\
"""

_FENCE_RE = re.compile(r"```(?:json)?\s*([\s\S]*?)```", re.IGNORECASE)
_TOOL_RESPONSE_RE = re.compile(r"<tool_response>\s*([\s\S]*?)\s*</tool_response>", re.IGNORECASE)
_TOOL_RESPONSE_BLOCK_RE = re.compile(r"(<tool_response>\s*[\s\S]*?\s*</tool_response>)", re.IGNORECASE)
_LOOSE_TOOL_RESPONSE_RE = re.compile(
    r"<tool_response>\s*([\s\S]*?)\s*</(?:tool_response|tool_call)>",
    re.IGNORECASE,
)
_UNTERMINATED_ASSISTANT_RESPONSE_RE = re.compile(
    r"<tool_response>[\s\S]*?(?=^\s*assistant|\Z)",
    re.IGNORECASE | re.MULTILINE,
)
_TOOL_CALL_BLOCK_RE = re.compile(r"<tool_call>\s*([\s\S]*?)\s*</tool_call>", re.IGNORECASE)
_THINK_PREFIX_RE = re.compile(r"^<think>\s*([\s\S]*?)\s*</think>", re.IGNORECASE)
_THINK_BLOCK_RE = re.compile(r"<think>\s*[\s\S]*?\s*</think>", re.IGNORECASE)
_ROLE_MARKER_RE = re.compile(r"(?m)^\s*(?:assistant|user)\s*")
_TOOLS_MARKER_RE = re.compile(r"(?m)^# Tools\s*$", re.IGNORECASE)


@dataclass(frozen=True, slots=True)
class RefineStats:
    """Summary returned after writing one refined Parquet file."""

    total: int
    refined: int
    failed: int


def _json_values(text: str) -> list[Any]:
    """Return JSON objects/lists found in a possibly decorated model reply."""
    stripped = text.strip()
    sources = [stripped, *[match.strip() for match in _FENCE_RE.findall(stripped)]]
    decoder = json.JSONDecoder()
    values: list[Any] = []
    seen: set[str] = set()

    for source in sources:
        if source and source not in seen:
            seen.add(source)
            try:
                values.append(json.loads(source))
                continue
            except json.JSONDecodeError:
                pass
        for index, char in enumerate(source):
            if char not in "[{":
                continue
            try:
                value, _ = decoder.raw_decode(source[index:])
            except json.JSONDecodeError:
                continue
            values.append(value)
    return values


def _validate_messages(messages: Any) -> list[JsonDict]:
    """Validate the structural and v1 reasoning contract of refined messages."""
    if not isinstance(messages, list) or not messages:
        raise ValueError("refiner output must contain a non-empty messages list")

    normalized: list[JsonDict] = []
    tool_call_count = 0
    tool_response_count = 0
    pending_tool_responses = 0
    for index, raw_message in enumerate(messages):
        if not isinstance(raw_message, Mapping):
            raise ValueError(f"messages[{index}] must be an object")
        role = raw_message.get("role")
        content = raw_message.get("content")
        if role not in {"system", "user", "assistant"}:
            raise ValueError(f"messages[{index}] has unsupported role {role!r}")
        if not isinstance(content, str) or not content.strip():
            raise ValueError(f"messages[{index}].content must be a non-empty string")

        if role == "assistant":
            if pending_tool_responses:
                raise ValueError(
                    f"messages[{index}] appears before {pending_tool_responses} pending tool responses"
                )
            if _TOOL_RESPONSE_RE.search(content):
                raise ValueError(f"messages[{index}] embeds a tool response in assistant content")
            think = _THINK_PREFIX_RE.match(content)
            if think is None or not think.group(1).strip():
                raise ValueError(f"messages[{index}] must start with a non-empty <think> block")
            raw_call_count = content.lower().count("<tool_call>")
            calls = extract_tool_calls(content)
            if raw_call_count != len(calls):
                raise ValueError(f"messages[{index}] contains an invalid tool call")
            tool_call_count += len(calls)
            pending_tool_responses = len(calls)
            if index != len(messages) - 1 and not calls:
                next_message = messages[index + 1]
                next_content = str(next_message.get("content", "")) if isinstance(next_message, Mapping) else ""
                if not (
                    isinstance(next_message, Mapping)
                    and next_message.get("role") == "user"
                    and not _TOOL_RESPONSE_RE.search(next_content)
                ):
                    raise ValueError(
                        f"non-final assistant message {index} without a tool call must precede a user follow-up"
                    )
        elif role == "user":
            response_count = len(_TOOL_RESPONSE_RE.findall(content))
            if response_count:
                if _TOOL_RESPONSE_BLOCK_RE.sub("", content).strip():
                    raise ValueError(f"messages[{index}] mixes tool responses with other user content")
                if response_count > pending_tool_responses:
                    raise ValueError(f"messages[{index}] has an unexpected tool response")
                pending_tool_responses -= response_count
                tool_response_count += response_count
            elif pending_tool_responses:
                raise ValueError(
                    f"messages[{index}] is an ordinary user turn before "
                    f"{pending_tool_responses} pending tool responses"
                )
        elif pending_tool_responses:
            raise ValueError(f"messages[{index}] appears before pending tool responses")

        normalized.append({"role": role, "content": content.strip()})

    if normalized[0]["role"] != "system":
        raise ValueError("refined messages must start with a system message")
    if normalized[-1]["role"] != "assistant":
        raise ValueError("refined messages must end with an assistant message")
    if extract_tool_calls(normalized[-1]["content"]):
        raise ValueError("final assistant message must not call a tool")
    if not extract_smiles_candidates(normalized[-1]["content"]):
        raise ValueError("final assistant message has no valid smiles answer object")
    if tool_call_count != tool_response_count:
        raise ValueError(
            f"tool call/response count mismatch: {tool_call_count} calls vs {tool_response_count} responses"
        )
    if pending_tool_responses:
        raise ValueError(f"trajectory ends before {pending_tool_responses} pending tool responses")
    return normalized


def parse_assistant_rewrites(response: str) -> dict[int, str]:
    """Extract ``message_index -> reasoning`` from a teacher-model response."""
    errors: list[str] = []
    for value in _json_values(response):
        if not isinstance(value, Mapping):
            continue
        candidate = value.get("assistant_rewrites")
        if not isinstance(candidate, list):
            continue

        rewrites: dict[int, str] = {}
        try:
            for position, item in enumerate(candidate):
                if not isinstance(item, Mapping):
                    raise ValueError(f"assistant_rewrites[{position}] must be an object")
                message_index = item.get("message_index")
                reasoning = item.get("reasoning")
                if not isinstance(message_index, int) or isinstance(message_index, bool):
                    raise ValueError(f"assistant_rewrites[{position}].message_index must be an integer")
                if message_index in rewrites:
                    raise ValueError(f"duplicate assistant rewrite for message_index {message_index}")
                if not isinstance(reasoning, str) or not reasoning.strip():
                    raise ValueError(f"assistant_rewrites[{position}].reasoning must be non-empty")
                if re.search(r"</?(?:think|tool_call|tool_response)\b", reasoning, re.IGNORECASE):
                    raise ValueError(f"assistant rewrite {message_index} contains a forbidden format tag")
                rewrites[message_index] = reasoning.strip()
            return rewrites
        except ValueError as exc:
            errors.append(str(exc))

    detail = errors[-1] if errors else "no assistant_rewrites JSON payload found"
    raise ValueError(f"invalid refiner response: {detail}")


def _current_system_prompt(source_messages: Sequence[Mapping[str, Any]]) -> str:
    """Combine the current think/RDKit prefix with the source tool schemas."""
    source_system = next(
        (str(message.get("content", "")) for message in source_messages if message.get("role") == "system"),
        "",
    )
    marker = _TOOLS_MARKER_RE.search(source_system)
    if marker is None:
        return SYSTEM_PROMPT_THINK_RDKIT
    tool_suffix = source_system[marker.start() :].strip()
    if "<tools>" not in tool_suffix or "</tools>" not in tool_suffix:
        raise ValueError("source system prompt has a malformed # Tools section")
    return f"{SYSTEM_PROMPT_THINK_RDKIT.rstrip()}\n\n{tool_suffix}"


def _normalize_assistant_content(content: str) -> str:
    """Drop model-fabricated embedded responses; real responses are separate user turns."""
    cleaned = _LOOSE_TOOL_RESPONSE_RE.sub("", content)
    cleaned = _UNTERMINATED_ASSISTANT_RESPONSE_RE.sub("", cleaned)
    cleaned = _ROLE_MARKER_RE.sub("", cleaned).strip()
    while cleaned.lower().count("<tool_call>") > cleaned.lower().count("</tool_call>"):
        match = re.search(r"<tool_call>\s*$", cleaned, re.IGNORECASE)
        if match is None:
            break
        cleaned = f"{cleaned[: match.start()].rstrip()}\n</tool_call>"
    if "<tool_response>" in cleaned.lower():
        raise ValueError("source assistant message contains an unterminated tool response")
    return cleaned


def _normalize_user_content(content: str) -> list[JsonDict]:
    """Preserve real response payloads while repairing only their XML end tags."""
    matches = list(_LOOSE_TOOL_RESPONSE_RE.finditer(content))
    if not matches:
        if "<tool_response>" in content.lower():
            raise ValueError("source user message contains an unterminated tool response")
        return [{"role": "user", "content": content.strip()}]

    outside = _LOOSE_TOOL_RESPONSE_RE.sub("", content)
    outside = _ROLE_MARKER_RE.sub("", outside).strip()
    if outside:
        raise ValueError("source user message mixes tool responses with ordinary content")
    return [
        {
            "role": "user",
            "content": f"<tool_response>\n{match.group(1).strip()}\n</tool_response>",
        }
        for match in matches
    ]


def _parse_source_tool_call(payload: str) -> JsonDict:
    """Parse common rollout JSON damage without involving the teacher model."""
    candidates = [payload.strip()]
    trimmed = payload.strip()
    for _ in range(3):
        if not trimmed.endswith("}"):
            break
        trimmed = trimmed[:-1].rstrip()
        candidates.append(trimmed)
    candidates.extend(f"{payload.strip()}{'}' * count}" for count in range(1, 4))

    for candidate in candidates:
        try:
            call = json.loads(candidate)
        except json.JSONDecodeError:
            continue
        if (
            isinstance(call, Mapping)
            and isinstance(call.get("name"), str)
            and isinstance(call.get("arguments"), Mapping)
        ):
            return {"name": call["name"], "arguments": dict(call["arguments"])}
    raise ValueError("invalid tool-call JSON")


def _source_tool_calls(content: str, *, message_index: int) -> list[JsonDict]:
    blocks = _TOOL_CALL_BLOCK_RE.findall(content)
    raw_call_count = content.lower().count("<tool_call>")
    if raw_call_count != len(blocks):
        raise ValueError(f"source assistant message {message_index} has an unterminated tool call")
    try:
        return [_parse_source_tool_call(payload) for payload in blocks]
    except ValueError as exc:
        raise ValueError(f"source assistant message {message_index} contains an invalid tool call") from exc


def _canonical_tool_call(call: Mapping[str, Any]) -> str:
    return f"<tool_call>\n{json.dumps(call, ensure_ascii=False)}\n</tool_call>"


def _align_tool_calls_with_responses(messages: list[JsonDict]) -> None:
    """Discard unexecuted calls and retain exactly one call per real response."""
    for index, message in enumerate(messages):
        if message["role"] != "assistant":
            continue
        call_matches = list(_TOOL_CALL_BLOCK_RE.finditer(message["content"]))
        if message["content"].lower().count("<tool_call>") != len(call_matches):
            raise ValueError(f"source assistant message {index} has an unterminated tool call")
        response_count = 0
        next_index = index + 1
        while next_index < len(messages):
            following = messages[next_index]
            if following["role"] != "user":
                break
            count = len(_TOOL_RESPONSE_RE.findall(following["content"]))
            if not count:
                break
            response_count += count
            next_index += 1

        if response_count > len(call_matches):
            raise ValueError(
                f"source assistant message {index} has {len(call_matches)} calls "
                f"but {response_count} following responses"
            )

        pieces: list[str] = []
        cursor = 0
        for call_index, match in enumerate(call_matches):
            pieces.append(message["content"][cursor : match.start()])
            if call_index < response_count:
                try:
                    call = _parse_source_tool_call(match.group(1))
                except ValueError as exc:
                    raise ValueError(
                        f"source assistant message {index} contains an invalid executed tool call"
                    ) from exc
                pieces.append(_canonical_tool_call(call))
            cursor = match.end()
        pieces.append(message["content"][cursor:])
        message["content"] = "".join(pieces).strip()


def _normalize_source_messages(messages: Sequence[Mapping[str, Any]]) -> list[JsonDict]:
    """Repair deterministic role boundaries without asking the teacher to copy evidence."""
    source = [
        {"role": str(message.get("role", "")), "content": str(message.get("content", ""))}
        for message in messages
    ]
    normalized: list[JsonDict] = []
    for index, message in enumerate(source):
        role = message["role"]
        content = message["content"]
        if role not in {"system", "user", "assistant"}:
            raise ValueError(f"source messages[{index}] has unsupported role {role!r}")
        if not content.strip():
            raise ValueError(f"source messages[{index}] has empty content")
        if role == "system":
            if normalized:
                raise ValueError("source system message must be first")
            normalized.append({"role": "system", "content": content.strip()})
        elif role == "assistant":
            cleaned = _normalize_assistant_content(content)
            if cleaned:
                cleaned = _inject_think_block(cleaned, message_index=index)
                normalized.append({"role": "assistant", "content": cleaned})
        else:
            normalized.extend(_normalize_user_content(content))

    if not normalized or normalized[0]["role"] != "system":
        raise ValueError("source messages must start with a system message")
    normalized[0]["content"] = _current_system_prompt(source)
    _align_tool_calls_with_responses(normalized)
    normalized = [message for message in normalized if message["role"] != "assistant" or message["content"]]
    has_tool_calls = any(
        message["role"] == "assistant" and "<tool_call>" in message["content"].lower()
        for message in normalized
    )
    if has_tool_calls and _TOOLS_MARKER_RE.search(normalized[0]["content"]) is None:
        raise ValueError("source system prompt is missing tool descriptions for a tool-calling trajectory")
    return normalized


def _assistant_suffix(content: str, *, message_index: int) -> str:
    """Preserve calls or answers while dropping the old explanatory prose."""
    calls = _source_tool_calls(content, message_index=message_index)
    if calls:
        return "\n".join(_canonical_tool_call(call) for call in calls)

    candidates = extract_smiles_candidates(content)
    if candidates:
        return format_final_answer(candidates)

    preserved = _THINK_BLOCK_RE.sub("", content).strip()
    if not preserved:
        raise ValueError(f"source assistant message {message_index} has no preservable answer content")
    return preserved


def _inject_think_block(content: str, *, message_index: int) -> str:
    """Wrap assistant content in <think> if it lacks one, preserving tool calls and final answer."""
    if _THINK_PREFIX_RE.match(content):
        return content
    try:
        suffix = _assistant_suffix(content, message_index=message_index)
    except ValueError:
        return content
    reasoning = _TOOL_CALL_BLOCK_RE.sub("", content).strip()
    smiles = extract_smiles_candidates(reasoning)
    if smiles:
        reasoning = reasoning.replace(format_final_answer(smiles), "").strip()
    if not reasoning:
        return f"<think>\n{suffix}\n</think>"
    return f"<think>\n{reasoning}\n</think>\n{suffix}"


def _rebuild_messages(source: list[JsonDict], rewrites: Mapping[int, str]) -> list[JsonDict]:
    assistant_indices = [index for index, message in enumerate(source) if message["role"] == "assistant"]
    if set(rewrites) != set(assistant_indices):
        missing = sorted(set(assistant_indices) - set(rewrites))
        unexpected = sorted(set(rewrites) - set(assistant_indices))
        raise ValueError(f"assistant rewrite indices mismatch; missing={missing}, unexpected={unexpected}")

    rebuilt: list[JsonDict] = []
    for index, message in enumerate(source):
        if message["role"] != "assistant":
            rebuilt.append(dict(message))
            continue
        suffix = _assistant_suffix(message["content"], message_index=index)
        rebuilt.append(
            {
                "role": "assistant",
                "content": f"<think>\n{rewrites[index].strip()}\n</think>\n{suffix}",
            }
        )
    return _validate_messages(rebuilt)


class TrajectoryRefiner:
    """Refine one trajectory with an injected shared LLM client."""

    def __init__(self, llm: LlmClientProtocol, *, model_name: str = "") -> None:
        self.llm = llm
        self.model_name = model_name

    async def refine(self, messages: Sequence[Mapping[str, Any]]) -> list[JsonDict]:
        source = _normalize_source_messages(messages)
        assistant_indices = [index for index, message in enumerate(source) if message["role"] == "assistant"]
        for index in assistant_indices:
            _assistant_suffix(source[index]["content"], message_index=index)

        prompt_messages = [
            {"message_index": index, "role": message["role"], "content": message["content"]}
            for index, message in enumerate(source)
        ]
        user_prompt = json.dumps(
            {
                "messages": prompt_messages,
                "assistant_message_indices": assistant_indices,
            },
            ensure_ascii=False,
        )
        response = await self.llm.complete(REFINER_PROMPT, user_prompt)
        if not response:
            detail = self.llm.last_error or "empty model response"
            raise RuntimeError(f"trajectory refinement failed: {detail}")

        rewrites = parse_assistant_rewrites(response)
        return _rebuild_messages(source, rewrites)


def _selected_positions(length: int, rows: Sequence[int] | None) -> list[int]:
    if rows is None:
        return list(range(length))
    positions = list(dict.fromkeys(rows))
    if not positions:
        raise ValueError("at least one --row value is required when rows are supplied")
    invalid = [row for row in positions if row < 0 or row >= length]
    if invalid:
        raise IndexError(f"row indices out of range for {length} rows: {invalid}")
    return positions


async def refine_parquet(
    input_path: str | Path,
    output_path: str | Path,
    refiner: TrajectoryRefiner,
    *,
    rows: Sequence[int] | None = None,
    batch_size: int = DEFAULT_BATCH_SIZE,
    on_error: str = "keep",
    show_progress: bool = True,
) -> RefineStats:
    """Refine selected rows from ``input_path`` and write a new Parquet file.

    With ``rows=None`` every row is processed.  When row indices are supplied,
    only those zero-based source rows are written.  ``on_error="keep"`` keeps
    the original messages and records the failure in ``refine_status``;
    ``on_error="raise"`` aborts without writing the destination.
    """
    if batch_size < 1:
        raise ValueError("batch_size must be at least 1")
    if on_error not in {"keep", "raise"}:
        raise ValueError("on_error must be 'keep' or 'raise'")

    try:
        import pandas as pd
    except ImportError as exc:
        raise ImportError(
            "trajectory refinement requires pandas/pyarrow; install with `pip install spectune[data]`"
        ) from exc

    source_path = Path(input_path).expanduser().resolve()
    destination = Path(output_path).expanduser().resolve()
    if source_path == destination:
        raise ValueError("input and output paths must be different")

    frame = pd.read_parquet(source_path)
    if "messages" not in frame.columns:
        raise ValueError(f"{source_path} has no messages column")
    positions = _selected_positions(len(frame), rows)
    records = [
        {str(key): to_python(value) for key, value in frame.iloc[position].to_dict().items()}
        for position in positions
    ]

    async def refine_one(position: int, record: JsonDict) -> JsonDict:
        original = record.get("messages")
        if not isinstance(original, list):
            error = ValueError(f"source row {position} has no valid messages list")
        else:
            try:
                record["messages"] = await refiner.refine(original)
                record["refine_status"] = "refined"
                record["refine_error"] = None
                record["refine_model"] = refiner.model_name
                record["refine_source_row"] = position
                return record
            except Exception as exc:  # each row is isolated in keep mode
                error = exc

        if on_error == "raise":
            raise error
        record["refine_status"] = "error"
        record["refine_error"] = f"{type(error).__name__}: {error}"
        record["refine_model"] = refiner.model_name
        record["refine_source_row"] = position
        return record

    output_records: list[JsonDict] = []
    for start in range(0, len(records), batch_size):
        batch_records = records[start : start + batch_size]
        batch_positions = positions[start : start + batch_size]
        output_records.extend(
            await asyncio.gather(
                *(
                    refine_one(position, record)
                    for position, record in zip(batch_positions, batch_records, strict=True)
                )
            )
        )
        if show_progress:
            print(f"  refined {min(start + batch_size, len(records)):>6}/{len(records)}", flush=True)

    destination.parent.mkdir(parents=True, exist_ok=True)
    result_df = pd.DataFrame(output_records)
    if "reward_score" in result_df.columns:
        result_df = result_df[result_df["reward_score"] > 0]
    if "sample_id" in result_df.columns:
        result_df = result_df.drop_duplicates(subset="sample_id", keep="first")
    result_df["enable_thinking"] = None
    result_df.to_parquet(destination, index=False)
    refined_count = sum(record["refine_status"] == "refined" for record in output_records)
    failed_count = sum(record["refine_status"] == "error" for record in output_records)
    return RefineStats(
        total=len(result_df),
        refined=refined_count,
        failed=failed_count,
    )


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="python -m spectune.rollout.refine",
        description=(
            "Use a litellm teacher model to repair rollout messages after postprocess "
            "and write a refined Parquet file for multiturn SFT."
        ),
    )
    p.add_argument("--input", required=True, metavar="PATH", help="Input postprocessed SFT Parquet file.")
    p.add_argument("--output", required=True, metavar="PATH", help="Destination refined Parquet file.")
    p.add_argument("--model", required=True, metavar="NAME", help="litellm model name used as the refiner.")
    p.add_argument(
        "--row",
        action="append",
        type=int,
        default=None,
        metavar="INDEX",
        help="Refine only this zero-based source row; repeat for multiple rows. Defaults to all rows.",
    )
    p.add_argument("--temperature", type=float, default=0.2, metavar="T")
    p.add_argument("--top-p", type=float, default=0.95, metavar="P")
    p.add_argument("--max-tokens", type=int, default=DEFAULT_MAX_TOKENS, metavar="N")
    p.add_argument("--timeout", type=float, default=600.0, metavar="SECONDS")
    p.add_argument("--max-retries", type=int, default=2, metavar="N")
    p.add_argument("--max-concurrency", type=int, default=4, metavar="N")
    p.add_argument("--batch-size", type=int, default=DEFAULT_BATCH_SIZE, metavar="N")
    p.add_argument(
        "--on-error",
        choices=["keep", "raise"],
        default="keep",
        help="Keep the original row with error metadata, or abort the run (default: keep).",
    )
    p.add_argument("--no-progress", action="store_true", help="Suppress batch progress output.")
    return p


def main(argv: list[str] | None = None) -> None:
    parser = build_parser()
    args = parser.parse_args(argv)
    llm = create_llm_client(
        "litellm",
        model=args.model,
        temperature=args.temperature,
        top_p=args.top_p,
        max_tokens=args.max_tokens,
        timeout_s=args.timeout,
        max_retries=args.max_retries,
        max_concurrency=args.max_concurrency,
    )
    if not llm.available:
        parser.error(
            "litellm is not configured; set LITELLM_API_KEY and LITELLM_API_BASE "
            "(the model is supplied by --model)"
        )

    print(f"loading  {args.input}")
    stats = asyncio.run(
        refine_parquet(
            args.input,
            args.output,
            TrajectoryRefiner(llm, model_name=args.model),
            rows=args.row,
            batch_size=args.batch_size,
            on_error=args.on_error,
            show_progress=not args.no_progress,
        )
    )
    print(f"wrote    {stats.total} rows -> {args.output}")
    print(f"result   {stats.refined} refined, {stats.failed} failed")


if __name__ == "__main__":
    main()


__all__ = [
    "REFINER_PROMPT",
    "RefineStats",
    "TrajectoryRefiner",
    "build_parser",
    "main",
    "parse_assistant_rewrites",
    "refine_parquet",
]
